[project]
name = 'Network-Harmonization-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.harmonization-effort]
path = 'contracts/harmonization-effort.clar'
clarity_version = 2
epoch = 2.5

[contracts.superstring-detection]
path = 'contracts/superstring-detection.clar'
clarity_version = 2
epoch = 2.5

[contracts.universe-stability]
path = 'contracts/universe-stability.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
